spring:
  datasource:
    url: jdbc:mysql://192.168.1.14:3306/tacocloud
    username: root 
    password: root
  data:
    rest:
      base-path: /data-api
logging:
  file:
    path: var/logs/
    name: var/logs/TacoCloud.log
  level:
    root: INFO
    org:
      springframework:
        security: INFO
taco:
  orders:
    pageSize: 10
server: 
    address: localhost
    port: 9090