spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root 
    password: Nghia2508@
logging:
  file:
    path: var/logs/
    name: var/logs/TacoCloud.log
  level:
    root: INFO
    org:
      springframework:
        security: INFO
taco:
  orders:
    pageSize: 10