spring:
  datasource:
    url: jdbc:mysql://192.168.1.6:3306/tacocloud
    username: root 
    password: root
  data:
    rest:
      base-path: /data-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          # issuer-uri: http://localhost:9000/oauth2/jwks
          
logging:
  file:
    path: var/logs/
    name: var/logs/TacoCloud.log
  level:
    root: INFO
    org:
      springframework:
        security: INFO
taco:
  orders:
    pageSize: 10
server: 
    address: localhost
    port: 9090