spring:
  datasource:
    url: jdbc:mysql://204.0.137.204:3306/tacocloud
    username: root 
    password: root
logging:
  file:
    path: var/logs/
    name: var/logs/TacoCloud.log
  level:
    root: INFO
    org:
      springframework:
        security: INFO
taco:
  orders:
    pageSize: 10
server: 
    address: 204.0.137.204
    port: 9090