spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root 
    password: Nghia2508@
  data:
    rest:
      base-path: /data-api
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         jwk-set-uri: http://localhost:9000/oauth2/jwks
  #         # issuer-uri: http://localhost:9000/oauth2/jwks
  # artemis:
  #   host: artemis.tacocloud.com
  #   port: 61617
  #   user: tacoweb
  #   password: 13tm31n
  jms:
    template:
      default-destination: tacocloud.order.queue
          
logging:
  file:
    path: var/logs/
    name: var/logs/TacoCloud.log
  level:
    root: INFO
    org:
      springframework:
        security: INFO
taco:
  orders:
    pageSize: 10
server: 
    port: 8081 