spring:
  datasource:
    url: jdbc:mysql://204.0.137.204:3306/tacocloud
    username: root 
    password: root
server:
  port: 9000
manage:
  endpoints:
    web: 
      exposure:
        include: '*'
logging:
  level:
    org:
      springframework:
        security: trace